---
# tasks file for common
- name: install packages
  apt: name={{ item }} state=installed
  with_items:
      - git
      - maven
      - default-jdk

- name: Clone repo
  git:
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
   dest: /home/home_work/
   clone: yes

- name: Building war
  command: mvn -f /home/home_work/pom.xml package
