---
# tasks file for webserver

- name: install tomcat8
  apt: name=tomcat8 state=present

- name: Copying files to WebApps to webserver
  copy: src={{ src_folder }} dest={{ dest_folder }} remote_src=true

  notify:
      - restart tomcat8                          
